import { ConceptoContent, Hashtag, MultilingualText } from '../../core/models/content.model';

/**
 * Función helper para crear texto multiidioma
 */
function createMultilingualText(text: string): MultilingualText {
  return {
    es: text,
    en: text, // En producción, aquí irían las traducciones reales
    ca: text,
    val: text,
    gl: text,
    eu: text
  };
}

/**
 * Hashtags de ejemplo para conceptos feministas
 */
export const sampleHashtags: Hashtag[] = [
  { id: '1', nombre: 'Igualdad', slug: 'igualdad', descripcion: 'Igualdad de género' },
  { id: '2', nombre: 'Feminismo', slug: 'feminismo', descripcion: 'Movimiento feminista' },
  { id: '3', nombre: 'Derechos', slug: 'derechos', descripcion: 'Derechos de las mujeres' },
  { id: '4', nombre: 'Género', slug: 'genero', descripcion: 'Género y sexualidad' },
  { id: '5', nombre: 'Sociedad', slug: 'sociedad', descripcion: 'Sociedad y cultura' },
  { id: '6', nombre: 'Política', slug: 'politica', descripcion: 'Política y feminismo' },
  { id: '7', nombre: 'Economía', slug: 'economia', descripcion: 'Economía feminista' },
  { id: '8', nombre: 'Teoría', slug: 'teoria', descripcion: 'Teoría feminista' },
];

/**
 * Contenidos de ejemplo de conceptos feministas
 */
export const sampleContents: ConceptoContent[] = [
  {
    id: '1',
    slug: 'patriarcado',
    tipo: 'concepto',
    titulo: createMultilingualText('Patriarcado'),
    descripcion: createMultilingualText('El patriarcado es un sistema de organización social, política y económica que otorga privilegios y poder a los hombres sobre las mujeres. Este sistema se manifiesta en múltiples ámbitos: la familia, el trabajo, la política, la cultura y las instituciones. El patriarcado no solo afecta a las relaciones entre hombres y mujeres, sino que también establece jerarquías que benefician a ciertos grupos masculinos sobre otros, y sobre todo, sobre las mujeres. Este sistema se reproduce a través de la socialización, las leyes, las tradiciones y las estructuras de poder, perpetuando la desigualdad de género de generación en generación.'),
    descripcion_lectura_facil: createMultilingualText('El patriarcado es cuando los hombres tienen más poder que las mujeres en la sociedad. Este sistema existe desde hace mucho tiempo.'),
    hashtags: [sampleHashtags[4], sampleHashtags[7], sampleHashtags[1]],
    activo: true,
    fecha_publicacion: new Date('2024-01-15'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-01-10'),
    fecha_modificacion: new Date('2024-01-15'),
    referencias: [
      { titulo: 'El patriarcado', autor: 'Kate Millet', anio: 1970 }
    ]
  },
  {
    id: '2',
    slug: 'feminismo',
    tipo: 'concepto',
    titulo: createMultilingualText('Feminismo'),
    descripcion: createMultilingualText('El feminismo es un movimiento social, político y cultural que lucha por la igualdad de derechos, oportunidades y trato entre mujeres y hombres. Surgió históricamente como respuesta a la opresión sistemática de las mujeres y ha evolucionado a través de diferentes olas históricas. El feminismo no busca la superioridad de las mujeres sobre los hombres, sino la eliminación de todas las formas de discriminación y violencia basadas en el género. Abarca desde la lucha por derechos civiles y políticos hasta la transformación de las estructuras sociales, económicas y culturales que perpetúan la desigualdad. El feminismo reconoce la diversidad de experiencias de las mujeres y busca crear un mundo más justo para todas las personas.'),
    descripcion_lectura_facil: createMultilingualText('El feminismo lucha por la igualdad entre mujeres y hombres. Quiere que todas las personas tengan los mismos derechos.'),
    hashtags: [sampleHashtags[0], sampleHashtags[1], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-01-20'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-01-15'),
    fecha_modificacion: new Date('2024-01-20')
  },
  {
    id: '3',
    slug: 'genero',
    tipo: 'concepto',
    titulo: createMultilingualText('Género'),
    descripcion: createMultilingualText('Construcción social y cultural de las características, roles y comportamientos asociados a mujeres y hombres.'),
    descripcion_lectura_facil: createMultilingualText('El género son las ideas que la sociedad tiene sobre cómo deben ser las mujeres y los hombres. No es lo mismo que el sexo biológico.'),
    hashtags: [sampleHashtags[3], sampleHashtags[4], sampleHashtags[7]],
    activo: true,
    fecha_publicacion: new Date('2024-02-01'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-01-25'),
    fecha_modificacion: new Date('2024-02-01')
  },
  {
    id: '4',
    slug: 'brecha-salarial',
    tipo: 'concepto',
    titulo: createMultilingualText('Brecha salarial'),
    descripcion: createMultilingualText('La brecha salarial es la diferencia porcentual entre el salario promedio de las mujeres y el de los hombres que realizan trabajos equivalentes o de igual valor. Esta desigualdad se manifiesta de múltiples formas: las mujeres suelen cobrar menos por el mismo puesto, tienen menos acceso a puestos de responsabilidad y liderazgo, y los sectores laborales feminizados están peor remunerados. Las causas de la brecha salarial incluyen la discriminación directa, la segregación laboral horizontal y vertical, la penalización por maternidad, la menor capacidad de negociación salarial y la infravaloración del trabajo tradicionalmente realizado por mujeres. Esta brecha tiene consecuencias económicas a lo largo de toda la vida de las mujeres, afectando sus pensiones y su independencia económica.'),
    descripcion_lectura_facil: createMultilingualText('La brecha salarial es cuando las mujeres cobran menos dinero que los hombres por hacer el mismo trabajo.'),
    hashtags: [sampleHashtags[0], sampleHashtags[6], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-02-10'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-02-05'),
    fecha_modificacion: new Date('2024-02-10')
  },
  {
    id: '5',
    slug: 'empoderamiento',
    tipo: 'concepto',
    titulo: createMultilingualText('Empoderamiento'),
    descripcion: createMultilingualText('Proceso por el cual las mujeres ganan control sobre sus propias vidas y decisiones.'),
    descripcion_lectura_facil: createMultilingualText('Empoderamiento significa que las mujeres pueden tomar sus propias decisiones. Tienen poder sobre su vida.'),
    hashtags: [sampleHashtags[2], sampleHashtags[1], sampleHashtags[4]],
    activo: true,
    fecha_publicacion: new Date('2024-03-01'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-02-25'),
    fecha_modificacion: new Date('2024-03-01')
  },
  {
    id: '6',
    slug: 'sororidad',
    tipo: 'concepto',
    titulo: createMultilingualText('Sororidad'),
    descripcion: createMultilingualText('La sororidad es la solidaridad, hermandad y apoyo mutuo entre mujeres en su lucha común por la igualdad y contra la opresión patriarcal. Este concepto va más allá de la simple amistad o camaradería; implica reconocer que todas las mujeres, independientemente de sus diferencias, comparten experiencias de discriminación y opresión basadas en el género. La sororidad promueve la creación de redes de apoyo, el reconocimiento mutuo, la validación de las experiencias de otras mujeres y la construcción de alianzas para el cambio social. En lugar de competir entre sí o reproducir los valores patriarcales, las mujeres practican la sororidad para fortalecerse colectivamente y transformar las estructuras que las oprimen. Es un principio fundamental del feminismo que busca crear comunidades de apoyo y resistencia.'),
    descripcion_lectura_facil: createMultilingualText('La sororidad es la ayuda entre mujeres. Significa que las mujeres se apoyan unas a otras.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[0]],
    activo: true,
    fecha_publicacion: new Date('2024-03-15'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-03-10'),
    fecha_modificacion: new Date('2024-03-15')
  },
  {
    id: '7',
    slug: 'interseccionalidad',
    tipo: 'concepto',
    titulo: createMultilingualText('Interseccionalidad'),
    descripcion: createMultilingualText('La interseccionalidad es un concepto desarrollado por la académica Kimberlé Crenshaw que reconoce que las personas pueden experimentar múltiples formas de discriminación y opresión simultáneamente, y que estas formas se intersectan y se potencian entre sí. Por ejemplo, una mujer negra puede experimentar discriminación tanto por ser mujer como por ser negra, y estas formas de opresión no pueden separarse. La interseccionalidad considera factores como el género, la raza, la clase social, la orientación sexual, la identidad de género, la discapacidad, la edad y otros aspectos de la identidad. Este enfoque permite entender mejor las experiencias complejas de las personas y desarrollar estrategias de lucha más inclusivas que no dejen a nadie atrás. La interseccionalidad es fundamental para un feminismo verdaderamente inclusivo y transformador.'),
    descripcion_lectura_facil: createMultilingualText('La interseccionalidad dice que una persona puede sufrir discriminación por varios motivos. Por ejemplo, por ser mujer y por su color de piel.'),
    hashtags: [sampleHashtags[7], sampleHashtags[1], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-04-01'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-03-25'),
    fecha_modificacion: new Date('2024-04-01')
  },
  {
    id: '8',
    slug: 'cuota-genero',
    tipo: 'concepto',
    titulo: createMultilingualText('Cuota de género'),
    descripcion: createMultilingualText('Las cuotas de género son medidas de acción positiva que establecen un porcentaje mínimo obligatorio de mujeres en puestos de decisión, representación política, órganos directivos o espacios de poder. Estas medidas buscan corregir la histórica subrepresentación de las mujeres en los espacios donde se toman decisiones importantes que afectan a toda la sociedad. Las cuotas pueden aplicarse en el ámbito político (listas electorales, gobiernos), empresarial (consejos de administración), educativo (cátedras universitarias) y otros espacios de poder. Aunque son medidas temporales y controvertidas, han demostrado ser efectivas para acelerar la participación de las mujeres en la vida pública y política. Las cuotas no buscan privilegiar a las mujeres, sino compensar las barreras estructurales que históricamente las han excluido de estos espacios.'),
    descripcion_lectura_facil: createMultilingualText('Las cuotas de género dicen que debe haber un número mínimo de mujeres en puestos importantes. Por ejemplo, en el gobierno o las empresas.'),
    hashtags: [sampleHashtags[5], sampleHashtags[0], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-04-15'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-04-10'),
    fecha_modificacion: new Date('2024-04-15')
  },
  {
    id: '9',
    slug: 'androcentrismo',
    tipo: 'concepto',
    titulo: createMultilingualText('Androcentrismo'),
    descripcion: createMultilingualText('El androcentrismo es una perspectiva que coloca al hombre y a lo masculino como el centro, la norma y la medida de todas las cosas, mientras que las mujeres y lo femenino son considerados como secundarios, desviaciones o excepciones. Esta visión del mundo se manifiesta en múltiples ámbitos: la historia se cuenta desde la perspectiva masculina, el conocimiento científico se construye con hombres como sujetos de estudio, el lenguaje utiliza el masculino como genérico, y las experiencias masculinas se consideran universales. El androcentrismo hace invisible las contribuciones, experiencias y perspectivas de las mujeres, presentándolas como menos importantes o relevantes. Esta perspectiva sesgada ha influido en la construcción del conocimiento, las instituciones, las leyes y la cultura en general, perpetuando la desigualdad de género.'),
    descripcion_lectura_facil: createMultilingualText('El androcentrismo es ver el mundo solo desde el punto de vista de los hombres. Es como si solo los hombres fueran importantes.'),
    hashtags: [sampleHashtags[7], sampleHashtags[4], sampleHashtags[1]],
    activo: true,
    fecha_publicacion: new Date('2024-05-01'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-04-25'),
    fecha_modificacion: new Date('2024-05-01')
  },
  {
    id: '10',
    slug: 'coeducacion',
    tipo: 'concepto',
    titulo: createMultilingualText('Coeducación'),
    descripcion: createMultilingualText('La coeducación es un modelo educativo que promueve la educación conjunta de niñas y niños en igualdad de condiciones, eliminando los estereotipos de género y fomentando el desarrollo integral de todas las personas independientemente de su género. A diferencia de la educación mixta tradicional, que simplemente junta a niños y niñas en el mismo espacio pero mantiene roles diferenciados, la coeducación busca activamente cuestionar y transformar los estereotipos de género, promover la igualdad de oportunidades, y educar en valores de respeto, corresponsabilidad y no discriminación. La coeducación implica revisar los contenidos educativos, el lenguaje utilizado, los materiales didácticos, las actividades y la organización escolar para eliminar sesgos de género y crear un ambiente educativo verdaderamente igualitario.'),
    descripcion_lectura_facil: createMultilingualText('La coeducación es enseñar la igualdad en las escuelas. Niñas y niños aprenden que pueden hacer las mismas cosas.'),
    hashtags: [sampleHashtags[0], sampleHashtags[4], sampleHashtags[1]],
    activo: true,
    fecha_publicacion: new Date('2024-05-15'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-05-10'),
    fecha_modificacion: new Date('2024-05-15')
  },
  {
    id: '11',
    slug: 'luz-de-gas-gaslighting',
    tipo: 'concepto',
    titulo: createMultilingualText('Luz de gas (gaslighting)'),
    descripcion: createMultilingualText('El gaslighting o "luz de gas" es una forma de manipulación psicológica y abuso emocional en la que el agresor niega sistemáticamente la realidad vivida por la víctima, haciéndola dudar de su propia memoria, percepción, juicio o cordura. El término proviene de la obra de teatro "Gas Light" donde un marido manipula a su esposa haciéndola creer que está perdiendo la razón. Esta técnica de manipulación incluye negar eventos que ocurrieron, distorsionar la verdad, culpar a la víctima, minimizar sus sentimientos y crear confusión deliberadamente. El gaslighting es especialmente común en relaciones de pareja abusivas, pero también puede ocurrir en el ámbito laboral, familiar o social. Sus efectos pueden ser devastadores, llevando a la víctima a perder la confianza en sí misma, aislarse y desarrollar problemas de salud mental. Reconocer el gaslighting es el primer paso para protegerse de esta forma de abuso.'),
    descripcion_lectura_facil: createMultilingualText('Se niega lo que ella ha vivido o dicho. Se la hace dudar de su memoria o de si "está loca".'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-06-01'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-05-25'),
    fecha_modificacion: new Date('2024-06-01')
  },
  {
    id: '12',
    slug: 'micromachismos',
    tipo: 'concepto',
    titulo: createMultilingualText('Micromachismos'),
    descripcion: createMultilingualText('Los micromachismos son pequeñas actitudes, comportamientos y gestos cotidianos, aparentemente sutiles e incluso inconscientes, que refuerzan la desigualdad de género y la posición de dominio masculino sobre las mujeres. El término fue acuñado por el psicólogo Luis Bonino para describir estas formas de machismo que, aunque parecen menores, son muy efectivas para mantener el poder masculino. Ejemplos incluyen interrumpir constantemente a las mujeres, apropiarse de sus ideas, usar un tono condescendiente, asumir que las mujeres deben realizar tareas domésticas o de cuidado, o hacer comentarios que minimizan sus capacidades. Aunque cada micromachismo puede parecer insignificante, su repetición constante crea un ambiente hostil y refuerza la desigualdad estructural. Reconocer y cuestionar los micromachismos es fundamental para construir relaciones más igualitarias.'),
    descripcion_lectura_facil: createMultilingualText('Son actitudes pequeñas pero repetidas. Refuerzan que el hombre manda y la mujer se adapta.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[0]],
    activo: true,
    fecha_publicacion: new Date('2024-06-05'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-06-01'),
    fecha_modificacion: new Date('2024-06-05')
  },
  {
    id: '13',
    slug: 'invalidacion-emocional',
    tipo: 'concepto',
    titulo: createMultilingualText('Invalidación emocional'),
    descripcion: createMultilingualText('La invalidación emocional es un proceso mediante el cual se minimizan, ignoran, desacreditan o rechazan las emociones, sentimientos y experiencias emocionales de una persona. Esta forma de abuso psicológico puede manifestarse a través de frases como "no es para tanto", "estás exagerando", "no tienes razón para sentirte así", "deberías estar agradecida" o "otras personas tienen problemas peores". La invalidación emocional es especialmente común hacia las mujeres, cuyas emociones son frecuentemente deslegitimadas o atribuidas a su "naturaleza emocional" o a factores biológicos como la menstruación. Este proceso hace que la persona pierda confianza en sus propias percepciones emocionales, se sienta culpable por sus sentimientos y aprenda a reprimir sus emociones. La invalidación emocional puede tener efectos graves en la salud mental y el bienestar de las personas, especialmente cuando es sistemática y viene de personas cercanas o figuras de autoridad.'),
    descripcion_lectura_facil: createMultilingualText('Se minimizan sus emociones. Frases como "no es para tanto" anulan lo que siente.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-06-10'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-06-05'),
    fecha_modificacion: new Date('2024-06-10')
  },
  {
    id: '14',
    slug: 'interrupciones-constantes',
    tipo: 'concepto',
    titulo: createMultilingualText('Interrupciones constantes'),
    descripcion: createMultilingualText('Las interrupciones constantes son un fenómeno por el cual se corta frecuentemente la palabra a las mujeres en conversaciones, reuniones, debates o espacios de discusión, haciendo que su voz pierda valor y visibilidad. Este comportamiento, conocido también como "manterrupting" (man + interrupting), es una forma de micromachismo muy común que refleja y refuerza la desigualdad de género. Las investigaciones muestran que los hombres interrumpen significativamente más a las mujeres que a otros hombres, y que cuando las mujeres intentan intervenir, a menudo son ignoradas o interrumpidas nuevamente. Este fenómeno tiene consecuencias importantes: las mujeres tienen menos oportunidades de expresar sus ideas, sus contribuciones son menos reconocidas, y se refuerza la idea de que sus opiniones son menos valiosas. Las interrupciones constantes también pueden ocurrir en el ámbito laboral, donde las mujeres profesionales ven cómo sus propuestas son ignoradas hasta que un hombre las repite y recibe el crédito.'),
    descripcion_lectura_facil: createMultilingualText('Se le corta la palabra con frecuencia. Su voz pierde valor en conversaciones o reuniones.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[0]],
    activo: true,
    fecha_publicacion: new Date('2024-06-15'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-06-10'),
    fecha_modificacion: new Date('2024-06-15')
  },
  {
    id: '15',
    slug: 'apropiacion-de-ideas',
    tipo: 'concepto',
    titulo: createMultilingualText('Apropiación de ideas'),
    descripcion: createMultilingualText('La apropiación de ideas es una situación en la que una mujer aporta una idea, propuesta o solución en un espacio de trabajo, reunión o discusión, pero esta es ignorada o minimizada hasta que otra persona, generalmente un hombre, la repite y recibe el reconocimiento y el crédito por ella. Este fenómeno, también conocido como "hepeating" (he + repeating), es una forma de micromachismo muy común en entornos profesionales y académicos. La apropiación de ideas no solo roba el reconocimiento merecido a las mujeres, sino que también refuerza la invisibilización de sus contribuciones intelectuales y profesionales. Este comportamiento puede tener consecuencias graves en la carrera profesional de las mujeres, ya que sus ideas y capacidades no son reconocidas, lo que afecta su visibilidad, promoción y desarrollo profesional. La apropiación de ideas es especialmente problemática cuando ocurre sistemáticamente, creando un ambiente donde las mujeres sienten que sus contribuciones no son valoradas.'),
    descripcion_lectura_facil: createMultilingualText('Ella aporta una idea. Luego otro la repite y recibe el reconocimiento.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[6]],
    activo: true,
    fecha_publicacion: new Date('2024-06-20'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-06-15'),
    fecha_modificacion: new Date('2024-06-20')
  },
  {
    id: '16',
    slug: 'control-disfrazado-de-cuidado',
    tipo: 'concepto',
    titulo: createMultilingualText('Control disfrazado de cuidado'),
    descripcion: createMultilingualText('Forma de control en la que se toman decisiones por otra persona bajo la excusa de protegerla, limitando en realidad su libertad y autonomía.'),
    descripcion_lectura_facil: createMultilingualText('Se decide por ella "para protegerla". En realidad se limita su libertad.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-06-25'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-06-20'),
    fecha_modificacion: new Date('2024-06-25')
  },
  {
    id: '17',
    slug: 'culpabilizacion',
    tipo: 'concepto',
    titulo: createMultilingualText('Culpabilización'),
    descripcion: createMultilingualText('La culpabilización es un proceso de manipulación psicológica mediante el cual se responsabiliza a una persona, generalmente una mujer, de problemas, conflictos o situaciones negativas que no son su responsabilidad, haciendo que acabe sintiéndose culpable y pidiendo perdón sin haber cometido ninguna falta. Esta forma de abuso emocional es común en relaciones tóxicas y puede manifestarse de múltiples formas: culpar a la víctima por los problemas del agresor, hacerla responsable de las emociones de otros, o atribuirle la culpa de situaciones sobre las que no tiene control. La culpabilización sistemática puede llevar a la víctima a desarrollar un sentido de responsabilidad excesivo, a dudar constantemente de sí misma, y a asumir la culpa por cosas que no ha hecho. Este proceso es especialmente dañino porque erosiona la autoestima y la capacidad de la persona para establecer límites saludables, manteniéndola en una posición de sumisión y constante disculpa.'),
    descripcion_lectura_facil: createMultilingualText('Se la responsabiliza de problemas ajenos. Acaba pidiendo perdón sin haber hecho nada.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-07-01'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-06-25'),
    fecha_modificacion: new Date('2024-07-01')
  },
  {
    id: '18',
    slug: 'doble-estandar',
    tipo: 'concepto',
    titulo: createMultilingualText('Doble estándar'),
    descripcion: createMultilingualText('El doble estándar es la aplicación de criterios, normas o expectativas diferentes para juzgar, evaluar o tratar el mismo comportamiento, actitud o situación según el género de la persona, siendo sistemáticamente más crítico, restrictivo o punitivo con las mujeres y más permisivo, comprensivo o justificativo con los hombres. Este fenómeno se manifiesta en múltiples ámbitos: en la sexualidad (las mujeres son juzgadas por tener múltiples parejas mientras que los hombres son elogiados), en la expresión emocional (las mujeres son "dramáticas" mientras que los hombres son "apasionados"), en el liderazgo (las mujeres son "mandonas" mientras que los hombres son "líderes"), o en la apariencia física (las mujeres deben cumplir estándares estrictos mientras que los hombres tienen más libertad). El doble estándar refleja y refuerza los estereotipos de género y la desigualdad, creando condiciones diferentes para mujeres y hombres que limitan las oportunidades y la libertad de las mujeres. Reconocer y cuestionar el doble estándar es fundamental para construir una sociedad más igualitaria.'),
    descripcion_lectura_facil: createMultilingualText('Lo mismo se juzga distinto según el sexo. En ella se critica, en ellos se justifica.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[0]],
    activo: true,
    fecha_publicacion: new Date('2024-07-05'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-07-01'),
    fecha_modificacion: new Date('2024-07-05')
  },
  {
    id: '19',
    slug: 'hipersexualizacion',
    tipo: 'concepto',
    titulo: createMultilingualText('Hipersexualización'),
    descripcion: createMultilingualText('La hipersexualización es un proceso mediante el cual se valora, enfatiza y reduce a las mujeres principalmente o exclusivamente a su cuerpo, apariencia física y sexualidad, ignorando, minimizando o invisibilizando sus capacidades intelectuales, profesionales, emocionales, ideas, talentos y aportaciones como personas completas. Este fenómeno se manifiesta en múltiples formas: la representación de las mujeres en los medios de comunicación centrada en su aspecto físico, la presión constante por cumplir estándares de belleza, el uso del cuerpo femenino como objeto de consumo, o la reducción de las mujeres a su atractivo sexual. La hipersexualización tiene consecuencias graves: limita las oportunidades de las mujeres, afecta su autoestima y salud mental, perpetúa estereotipos de género, y crea un ambiente donde las mujeres son valoradas principalmente por su apariencia en lugar de sus capacidades y contribuciones. Este proceso comienza desde la infancia y afecta a las mujeres a lo largo de toda su vida, limitando su desarrollo personal y profesional.'),
    descripcion_lectura_facil: createMultilingualText('Se valora más su cuerpo que su persona. Se ignoran sus capacidades o ideas.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-07-10'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-07-05'),
    fecha_modificacion: new Date('2024-07-10')
  },
  {
    id: '20',
    slug: 'invisibilizacion-profesional',
    tipo: 'concepto',
    titulo: createMultilingualText('Invisibilización profesional'),
    descripcion: createMultilingualText('La invisibilización profesional es un fenómeno por el cual el trabajo, las contribuciones y los logros profesionales de las mujeres no se reconocen, valoran o visibilizan adecuadamente, asumiéndose que "solo ayuda", que es secundario, o que no es clave para el resultado final. Este fenómeno se manifiesta de múltiples formas: las mujeres realizan trabajo esencial pero no reciben crédito, sus ideas son apropiadas por otros, sus logros son atribuidos a la suerte o a factores externos, o se asume que su trabajo es menos importante o complejo que el de los hombres. La invisibilización profesional también incluye la falta de reconocimiento del trabajo emocional y de cuidado que realizan las mujeres, que aunque es esencial, rara vez se valora económicamente o profesionalmente. Este fenómeno tiene consecuencias graves en la carrera profesional de las mujeres: menos oportunidades de promoción, menor reconocimiento público, salarios más bajos, y una sensación constante de que su trabajo no es valorado. La invisibilización profesional refuerza la desigualdad de género en el ámbito laboral y limita las oportunidades de desarrollo profesional de las mujeres.'),
    descripcion_lectura_facil: createMultilingualText('Su trabajo no se reconoce. Se asume que "solo ayuda" o que no es clave.'),
    hashtags: [sampleHashtags[1], sampleHashtags[6], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-07-15'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-07-10'),
    fecha_modificacion: new Date('2024-07-15')
  },
  {
    id: '21',
    slug: 'sobrecarga-mental',
    tipo: 'concepto',
    titulo: createMultilingualText('Sobrecarga mental'),
    descripcion: createMultilingualText('Expectativa social de que las mujeres recuerden y organicen todo, siendo un esfuerzo invisible que no se reconoce ni se reparte equitativamente.'),
    descripcion_lectura_facil: createMultilingualText('Se espera que lo recuerde y organice todo. Nadie ve ese esfuerzo ni lo reparte.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[6]],
    activo: true,
    fecha_publicacion: new Date('2024-07-20'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-07-15'),
    fecha_modificacion: new Date('2024-07-20')
  },
  {
    id: '22',
    slug: 'infantilizacion',
    tipo: 'concepto',
    titulo: createMultilingualText('Infantilización'),
    descripcion: createMultilingualText('La infantilización es el trato hacia las mujeres como si fueran menores de edad o personas incapaces, dudando sistemáticamente de su capacidad para entender, decidir, gestionar o actuar por sí mismas de manera competente. Este fenómeno se manifiesta a través de un lenguaje condescendiente, explicaciones innecesarias de cosas obvias, la asunción de que las mujeres necesitan protección o guía constante, o el cuestionamiento de sus decisiones y capacidades. La infantilización puede ocurrir en múltiples contextos: en relaciones de pareja, en el ámbito laboral, en el ámbito médico, o en las interacciones sociales cotidianas. Este trato paternalista y condescendiente niega la agencia, autonomía y competencia de las mujeres, tratándolas como si fueran incapaces de tomar decisiones informadas o de manejar situaciones complejas. La infantilización es especialmente problemática porque erosiona la confianza de las mujeres en sí mismas, limita su autonomía, y refuerza la idea de que necesitan la protección o guía de los hombres. Este fenómeno refleja y perpetúa la desigualdad de género al negar la capacidad de las mujeres para ser agentes autónomos y competentes.'),
    descripcion_lectura_facil: createMultilingualText('Se le habla como si no entendiera. Se duda de su capacidad para decidir.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-07-25'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-07-20'),
    fecha_modificacion: new Date('2024-07-25')
  },
  {
    id: '23',
    slug: 'bromas-sexistas',
    tipo: 'concepto',
    titulo: createMultilingualText('Bromas sexistas'),
    descripcion: createMultilingualText('Comentarios machistas presentados como humor, que cuando molestan a las mujeres, generan acusaciones de exageración o falta de sentido del humor.'),
    descripcion_lectura_facil: createMultilingualText('Comentarios machistas presentados como humor. Si molesta, se la acusa de exagerar.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[0]],
    activo: true,
    fecha_publicacion: new Date('2024-08-01'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-07-25'),
    fecha_modificacion: new Date('2024-08-01')
  },
  {
    id: '24',
    slug: 'silenciamiento',
    tipo: 'concepto',
    titulo: createMultilingualText('Silenciamiento'),
    descripcion: createMultilingualText('El silenciamiento es un proceso mediante el cual se ignoran, minimizan o desacreditan sistemáticamente las opiniones, ideas, propuestas y voces de las mujeres, escuchándolas y valorándolas solo cuando son repetidas, respaldadas o presentadas por otra persona, generalmente un hombre. Este fenómeno se manifiesta cuando una mujer expresa una idea que es ignorada, pero cuando un hombre repite la misma idea, recibe atención, reconocimiento y crédito. El silenciamiento también puede ocurrir cuando las mujeres son interrumpidas constantemente, cuando sus contribuciones son atribuidas a otros, o cuando se asume que sus opiniones son menos válidas o importantes. Este proceso tiene consecuencias graves: las mujeres tienen menos oportunidades de expresarse, sus contribuciones intelectuales y profesionales no son reconocidas, y se refuerza la idea de que sus voces son menos valiosas. El silenciamiento es especialmente común en espacios profesionales, académicos y políticos, donde las mujeres luchan por ser escuchadas y reconocidas. Este fenómeno perpetúa la desigualdad de género al negar la agencia intelectual y la capacidad de las mujeres para contribuir significativamente a los debates y decisiones importantes.'),
    descripcion_lectura_facil: createMultilingualText('Se ignoran sus opiniones. Solo se la escucha cuando otro las repite.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-08-05'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-08-01'),
    fecha_modificacion: new Date('2024-08-05')
  },
  {
    id: '25',
    slug: 'dependencia-economica-inducida',
    tipo: 'concepto',
    titulo: createMultilingualText('Dependencia económica inducida'),
    descripcion: createMultilingualText('Estrategia de control que limita el acceso de las mujeres al dinero o al trabajo, reduciendo su autonomía y poder de decisión.'),
    descripcion_lectura_facil: createMultilingualText('Se limita su acceso al dinero o al trabajo. Así pierde autonomía y poder de decisión.'),
    hashtags: [sampleHashtags[1], sampleHashtags[6], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-08-10'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-08-05'),
    fecha_modificacion: new Date('2024-08-10')
  },
  {
    id: '26',
    slug: 'presion-estetica-constante',
    tipo: 'concepto',
    titulo: createMultilingualText('Presión estética constante'),
    descripcion: createMultilingualText('La presión estética constante es la exigencia social, cultural y mediática de que las mujeres cumplan con ideales de belleza específicos, estrictos y frecuentemente inalcanzables, haciendo que su valor, éxito y aceptación social parezcan depender principalmente de su aspecto físico. Esta presión se manifiesta a través de múltiples canales: los medios de comunicación, la publicidad, las redes sociales, las industrias de la moda y la belleza, y las interacciones sociales cotidianas. La presión estética constante incluye expectativas sobre el peso, la forma del cuerpo, el tipo de piel, el cabello, la edad aparente, y múltiples otros aspectos físicos. Esta presión tiene consecuencias graves: trastornos alimentarios, problemas de salud mental, gastos económicos significativos en productos y servicios de belleza, y una constante sensación de insuficiencia. La presión estética constante limita las oportunidades de las mujeres, consume su tiempo y energía, y refuerza la idea de que su valor principal reside en su apariencia física en lugar de sus capacidades, talentos o contribuciones. Esta presión comienza desde la infancia y afecta a las mujeres a lo largo de toda su vida, creando un ciclo constante de insatisfacción y esfuerzo por cumplir estándares imposibles.'),
    descripcion_lectura_facil: createMultilingualText('Se exige que cumpla un ideal de belleza. Su valor parece depender de su aspecto.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-08-15'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-08-10'),
    fecha_modificacion: new Date('2024-08-15')
  },
  {
    id: '27',
    slug: 'deslegitimar-el-enfado',
    tipo: 'concepto',
    titulo: createMultilingualText('Deslegitimar el enfado'),
    descripcion: createMultilingualText('La deslegitimación del enfado es un proceso mediante el cual cuando una mujer expresa enfado, ira o frustración, se la ridiculiza, minimiza, desacredita o se cuestiona su reacción, sin tomar en serio sus emociones, preocupaciones o razones para estar molesta. Este fenómeno se manifiesta a través de respuestas como "estás exagerando", "estás siendo dramática", "estás histérica", "deberías calmarte", o atribuir su enfado a factores biológicos como la menstruación o la menopausia. Cuando los hombres expresan enfado, frecuentemente son vistos como "apasionados", "firmes" o "líderes", mientras que el mismo comportamiento en las mujeres es deslegitimado y ridiculizado. La deslegitimación del enfado tiene consecuencias importantes: las mujeres aprenden a reprimir sus emociones legítimas, se sienten culpables por expresar su malestar, y sus preocupaciones y límites no son respetados. Este proceso refuerza la idea de que las emociones de las mujeres son irracionales o inválidas, y limita su capacidad para establecer límites saludables y expresar sus necesidades. La deslegitimación del enfado es una forma de control que mantiene a las mujeres en una posición de sumisión y silencia sus voces cuando expresan descontento legítimo.'),
    descripcion_lectura_facil: createMultilingualText('Cuando se enfada, se la ridiculiza. Su enfado no se toma en serio.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-08-20'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-08-15'),
    fecha_modificacion: new Date('2024-08-20')
  },
  {
    id: '28',
    slug: 'expectativa-de-cuidados',
    tipo: 'concepto',
    titulo: createMultilingualText('Expectativa de cuidados'),
    descripcion: createMultilingualText('La expectativa de cuidados es la presión social y cultural de que las mujeres deben cuidar de otras personas (hijos, familiares mayores, personas enfermas, parejas) sin necesidad de que se les pida explícitamente, asumiéndose que "se les da mejor" o que es su "naturaleza" por ser mujeres. Esta expectativa se basa en estereotipos de género que asocian a las mujeres con roles de cuidado y crianza, y se manifiesta en múltiples formas: se espera que las mujeres asuman automáticamente las responsabilidades de cuidado, se les atribuyen estas tareas sin consultarles, y se asume que disfrutan o están naturalmente capacitadas para realizarlas. La expectativa de cuidados tiene consecuencias importantes: las mujeres dedican significativamente más tiempo al trabajo de cuidados no remunerado, tienen menos oportunidades para el desarrollo profesional y personal, experimentan mayor agotamiento y estrés, y esta labor esencial rara vez se reconoce o valora adecuadamente. Esta expectativa desigual perpetúa la división sexual del trabajo y limita las oportunidades de las mujeres, mientras que los hombres rara vez enfrentan las mismas expectativas de cuidado. La expectativa de cuidados es una forma de desigualdad de género que afecta profundamente la vida de las mujeres y perpetúa roles de género restrictivos.'),
    descripcion_lectura_facil: createMultilingualText('Se espera que cuide sin pedirlo. Porque "se le da mejor" por ser mujer.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[0]],
    activo: true,
    fecha_publicacion: new Date('2024-08-25'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-08-20'),
    fecha_modificacion: new Date('2024-08-25')
  },
  {
    id: '29',
    slug: 'aislamiento-sutil',
    tipo: 'concepto',
    titulo: createMultilingualText('Aislamiento sutil'),
    descripcion: createMultilingualText('El aislamiento sutil es una estrategia de control y abuso que consiste en criticar sistemáticamente el entorno de la víctima (amigos, familia, compañeros de trabajo), generar conflictos, crear desconfianza, o hacer que la víctima se distancie de su red de apoyo, logrando que poco a poco se quede sola y dependiente del agresor. A diferencia del aislamiento abierto y directo, el aislamiento sutil es más insidioso porque se presenta como preocupación o protección, haciendo que la víctima crea que está tomando decisiones propias cuando en realidad está siendo manipulada. Esta estrategia puede incluir comentarios negativos sobre las personas cercanas a la víctima, crear conflictos artificiales, hacer que la víctima se sienta culpable por pasar tiempo con otros, o presentar al agresor como la única persona que realmente la entiende o la cuida. El aislamiento sutil tiene consecuencias graves: la víctima pierde su red de apoyo, se vuelve más dependiente del agresor, tiene menos recursos para reconocer el abuso, y es más vulnerable a la manipulación. Esta estrategia es especialmente común en relaciones de pareja abusivas y es una forma efectiva de mantener el control sobre la víctima al limitar sus fuentes de información, apoyo y perspectiva externa.'),
    descripcion_lectura_facil: createMultilingualText('Se critica a su entorno o se genera conflicto. Poco a poco se queda sola.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[2]],
    activo: true,
    fecha_publicacion: new Date('2024-09-01'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-08-25'),
    fecha_modificacion: new Date('2024-09-01')
  },
  {
    id: '30',
    slug: 'negacion-del-machismo',
    tipo: 'concepto',
    titulo: createMultilingualText('Negación del machismo'),
    descripcion: createMultilingualText('La negación del machismo es un discurso que afirma que el machismo, la discriminación de género y la desigualdad "ya no existen" o que son problemas del pasado, invalidando así las experiencias, el sufrimiento y las luchas reales y actuales de las mujeres. Este discurso se manifiesta a través de frases como "ya tenemos igualdad", "el machismo es cosa del pasado", "las mujeres ya tienen todos los derechos", "ahora las mujeres tienen más privilegios que los hombres", o "estás exagerando, eso ya no pasa". La negación del machismo es especialmente problemática porque invisibiliza las formas actuales de discriminación y violencia, deslegitima las experiencias de las mujeres, y crea resistencia al cambio y a las políticas de igualdad. Este discurso ignora las estadísticas sobre violencia de género, brecha salarial, desigualdad en el acceso al poder, y otras formas sistemáticas de discriminación que siguen existiendo. La negación del machismo también puede manifestarse como "backlash" o reacción contra los avances feministas, presentando la lucha por la igualdad como innecesaria o excesiva. Este discurso tiene consecuencias importantes: dificulta el reconocimiento de problemas reales, limita el apoyo a políticas de igualdad, y hace que las mujeres se sientan invalidadas cuando expresan sus experiencias de discriminación. La negación del machismo es una forma de mantener el statu quo y resistirse al cambio hacia una sociedad más igualitaria.'),
    descripcion_lectura_facil: createMultilingualText('Se dice que "ya no existe". Así se invalida lo que ella sufre.'),
    hashtags: [sampleHashtags[1], sampleHashtags[4], sampleHashtags[0]],
    activo: true,
    fecha_publicacion: new Date('2024-09-05'),
    estado: 'publicado',
    fecha_creacion: new Date('2024-09-01'),
    fecha_modificacion: new Date('2024-09-05')
  }
];

